
services:
  web:
    image: my-flask-redis:latest
    ports:
      - "5002:5002"
    depends_on:
      - redis

  redis:
    image: redis:7.4.5-alpine
    ports: 
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: