FROM python:3.8-slim

WORKDIR /app

COPY . .

RUN apt-get update && apt-get install -y \
    gcc \
    python3-dev \
    pkg-config

RUN pip install flask flask-redis

EXPOSE 5002

CMD ["python", "app.py"]
